name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create deployment zip
        working-directory: backend
        run: zip -r ../deploy.zip app/ Procfile requirements.txt

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          application_name: Coherence
          environment_name: Coherence-env
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
